### ISSUE TITLE
Extend TimeArray constructors found in TimeSeries package

### ISSUE THREAD

**Issue by milktrader** [femtotrader/TimeSeriesIO.jl#2]
``` julia
julia> using TimeSeries

julia> TimeArray() = println("I'm an new constructor")
TimeArray (generic function with 1 method)

julia> TimeArray()
I'm an new constructor
```

**Comment by femtotrader** [comment]
See  [renamed_func branch](https://github.com/femtotrader/TimeSeriesReader.jl/tree/renamed_func)
I'm getting:

``` julia
ERROR: LoadError: MethodError: no method matching TimeArray(::Array{Date,1}, ::Array{Float64,2}, ::Array{String,1})
 in #TimeArray#1(::Symbol, ::Array{Symbol,1}, ::Function, ::DataFrames.DataFrame) at /Users/femto/.julia/v0.5/TimeSeriesReader/src/TimeSeriesReader.jl:18
 in (::TimeSeriesReader.#kw##TimeArray)(::Array{Any,1}, ::TimeSeriesReader.#TimeArray, ::DataFrames.DataFrame) at ./<missing>:0
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
 in _start() at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
while loading /Users/femto/.julia/v0.5/TimeSeriesReader/test/runtests.jl, in expression starting on line 23
```

Default constructor seems to be overriden

**Comment by milktrader** [comment]
You need to show more code and what you called to get the error. I can't reproduce something if I don't know what you did.

~~Whatever argument you called it was not a DataFrame, it was three Arrays~~

It's the call to construct a TimeArray inside your method that's broke.

**Comment by femtotrader** [comment]
> You need to show more code and what you called to get the error. I can't reproduce something if I don't know what you did.

Just run tests in `renamed_func` branch

```
julia test/runtests.jl
```

> It's the call to construct a TimeArray inside your method that's broke.

that's the reason I'm saying "Default constructor seems to be overriden"

**Comment by milktrader** [comment]
Add this before defining TimeArray

`import TimeSeries.TimeArray`

**Comment by femtotrader** [comment]
Thanks @milktrader 

I need to understand more precisely differences between `import` and `using`

What is odd to me, for example, is that I need here to

``` julia
import TimeSeries.TimeArray
```

but I don't need

``` julia
import DataFrames.DataFrame
```

**Comment by milktrader** [comment]
Because you're overloading the TimeArray constructor, not the DataFrames constructor.

**Comment by femtotrader** [comment]
Sorry but I still don't understand why I'm overloading the TimeArray constructor, not the DataFrame constructor...

https://github.com/JuliaStats/TimeSeries.jl/blob/master/src/timearray.jl#L14
https://github.com/JuliaStats/DataFrames.jl/blob/master/src/dataframe/dataframe.jl#L76

**Comment by milktrader** [comment]
You're not creating a DataFrame are you? You don't need to extend that constructor (overload) if you're not. Unless you are elsewhere and then you need to overload it.

**Comment by femtotrader** [comment]
I'm also creating a DataFrame when a TimeArray is given.
see https://github.com/femtotrader/TimeSeriesReader.jl/blob/master/src/TimeSeriesReader.jl#L24
and its usage https://github.com/femtotrader/TimeSeriesReader.jl/blob/master/test/runtests.jl#L44
but I don't need here `import DataFrames.DataFrame`... so I'm wondering why.
Is it because TimeArrays are immutable and not DataFrames ?
